### ISSUE TITLE
Member party affiliation

### ISSUE THREAD

**Issue by joshtemple** [nysenate/OpenLegislation#104]
Hi! Thanks for this excellent and well-documented API.

Is there any way to get the party affiliation of a senate member? It doesn't seem to be a field available from the Members endpoint.

**Comment by KevinCaseiras** [comment]
Thanks for the feedback.

Open Legislation does not store party affiliation for members. However, nysenate.gov provides a json feed with senator information including their party, see https://www.nysenate.gov/senators-json
