### ISSUE TITLE
No Assembly Committees

### ISSUE THREAD

**Issue by samsullivan** [nysenate/OpenLegislation#11]
`GET /api/3/committees/2015/assembly` returns:

```
{
  "success": true,
  "message": "",
  "responseType": "empty list",
  "total": 0,
  "offsetStart": 1,
  "offsetEnd": 0,
  "limit": 50,
  "result": {
    "items": [],
    "size": 0
  }
}
```

It doesn't appear to be a code issue, but a missing data issue. There aren't any Assembly committees in a wildcard search: `GET /api/3/committees/2015/search?term=*`. This is true for all years.

**Comment by samsullivan** [comment]
This is especially surprising to me, since bill endpoints do mention committees from the Assembly:

```
{
  "success" : true,
  "message" : "Data for bill A330-2015",
  "result" : {
    "pastCommittees" : {
      "items" : [ {
        "chamber" : "ASSEMBLY",
        "name" : "Real Property Taxation",
        "sessionYear" : 2015,
        "referenceDate" : "2015-01-07T00:00"
      } ],
      "size" : 1
    },
    ...
  }
}
```

Yet, trying to access that committee fails...`GET /api/3/committees/2015/assembly/Real%20Property%20Taxation`:

```
{
  "success": false,
  "message": "The requested committee version was not found",
  "responseType": "error",
  "errorCode": 42,
  "errorData": {
    "chamber": "ASSEMBLY",
    "name": "Real Property Taxation",
    "sessionYear": 2015
  },
  "errorDataType": "committee-session-id"
}
```

**Comment by McSquirrel** [comment]
Hi Sam, 

This is, unfortunately, a data issue.  Currently, we do not have access to assembly committee data.  The same is also true for calendars and agendas/committee meetings and transcripts.  These endpoints were added in case we do eventually get access to this data.  

Sorry if this was misleading.

**Comment by samsullivan** [comment]
I understand the rationale behind having the endpoints available. I'd suggest adding a warning to the docs, but no worries.

Will you update this thread if you ever get the info or should I just check occasionally?

**Comment by McSquirrel** [comment]
We will try to make this more clear in the docs, thanks for the heads up!

If we get the data, or release any other modifications to the API, you can expect to get an email at the address you used to register for your key.

**Comment by samsullivan** [comment]
Great! Just a side note, I'm very impressed with the NY Senate's work. If I remember correctly, the API wasn't near as robust when I looked a few years back. Keep up the good work, we appreciate it.

Since I'll be getting email updates, I am closing the thread. Feel free to reopen it if you want to use it as a reminder for the docs.
