### ISSUE TITLE
Missing bill action from end of 2022 when compared to the Assembly website

### ISSUE THREAD

**Issue by dakshaau** [nysenate/OpenLegislation#113]
Hi,

I noticed that there are several bills that don't have a few actions available in the API response, but when looking at the Assembly counterpart, actions do seem to be available.

IDs that I have noticed so far:
- A 7006
- S 4104
- A 7063
- S 6291

Example for A 7006, [Assembly](https://assembly.state.ny.us/leg/?default_fld=&leg_video=&bn=S04104&term=2021&Actions=Y).
<img width="622" alt="Screen Shot 2023-01-04 at 12 34 38 PM" src="https://user-images.githubusercontent.com/6706064/210625592-25194a87-d9a6-4770-b8b8-fbc2444350f8.png">

[Substitute Bill actions](https://legislation.nysenate.gov/bills/2021/S4104?amendment=A&tab=Actions)
<img width="531" alt="Screen Shot 2023-01-04 at 12 39 54 PM" src="https://user-images.githubusercontent.com/6706064/210626818-4047f836-9870-499c-a49c-6df6cbb61ace.png">

Is this an expected behavior of the API/data? If not, is there any timeline on when these actions might be added on the OpenLegislation API?

**Comment by KevinCaseiras** [comment]
Thanks for your report.

We had some delays with processing legislative data around the new year. Everything should be up to date now.
