### ISSUE TITLE
Timing for 2023 session data

### ISSUE THREAD

**Issue by kenanokeefe** [nysenate/OpenLegislation#114]
Hello -

We are noticing a potential delay with 2023 session data from the API.

The [Assembly website](https://assembly.state.ny.us/leg/?sh=advanced) currently lists 848 bills that are not available via the [Senate API](https://legislation.nysenate.gov/api/3/bills/2023).

Thanks,
Kenan

**Comment by dakshaau** [comment]
Seeing the same issue. The total number of bills has increased to **963**.

**Comment by priyanka-salunke** [comment]
Yes, facing same issue . now total number of bills are 986.

**Comment by KevinCaseiras** [comment]
Applolgies for the delay in 2023 legislation data. We are processing as normal now and everything should be up to date.
