### ISSUE TITLE
Some members.items.fullName are invalid.

### ISSUE THREAD

**Issue by samsullivan** [nysenate/OpenLegislation#12]
Not sure if you guys want me to continue reporting data issues on this repo, but there is an issue with some legislators' names being incomplete and in all caps. The two instances in the 2015-16 session are both in the Assembly,

```
{
  "success": true,
  "responseType": "member list",
  "total": 213,
  ...
  "result": {
    "items": [
      {
        "memberId": 912,
        "shortName": "RICHARDSON",
        "sessionYear": 2015,
        "chamber": "ASSEMBLY",
        "fullName": "RICHARDSON",
        "districtCode": 0,
        "imgName": null
      },
      {
        "memberId": 901,
        "shortName": "JEAN-PIERRE",
        "sessionYear": 2015,
        "chamber": "ASSEMBLY",
        "fullName": "JEAN-PIERRE",
        "districtCode": 11,
        "imgName": "901_jean-pierre.jpg"
      },
      ...
    ],
    "size": 213
  }
}
```

**Comment by McSquirrel** [comment]
Hi Sam,

Thank you for bringing this to our attention.  We have to enter a lot of this member data manually and these two Assembly members were sworn in within the past year.  We are working to improve the workflow of identifying new members and filling in the data.

In the meantime, I will update our "unidentified" members and update this ticket when that is complete.

**Comment by samsullivan** [comment]
Great, I completely understand the pain of manually entering data. Hopefully the NY Assembly works closer with the Senate in the future! :smile:

**Comment by McSquirrel** [comment]
I have corrected the full name and district code issues for members in 2015.  There are still issues in past sessions, but they are not as straightforward and will be addressed later on.

Also, its ok to report data issues here and much appreciated!

**Comment by samsullivan** [comment]
Awesome, thanks! I've updated my data and all looks well.
