### ISSUE TITLE
VAT 1809 truncated

### ISSUE THREAD

**Issue by jurisware-devel** [nysenate/OpenLegislation#121]
Hello,

When I access the API for Vehicle and Traffic laws using https://legislation.nysenate.gov/api/3/laws/VAT?full=true&key=[my key], I see that V&T 1809 (a very lengthy section) is being truncated.  The end of the section text is:

"with school bus red visual\\nEZA5340I SMTP note from VISCUSI at LBDC was truncated by LBDCMVS1.LBDC.STATE.NY.US\\n\\n",

Thank you.

**Comment by KevinCaseiras** [comment]
Thank you for the report.

We have identified and corrected the issue. The full text for VAT 1809 is now available.
