### ISSUE TITLE
Missing Assembly Vote Information

### ISSUE THREAD

**Issue by jehiah** [nysenate/OpenLegislation#122]
The API seems to be missing Vote information for all Assembly bills (vote information for the senate does appear in the API).

For example `2021-A9275` had 3 votes in the Assembly that do not appear in the API response (the votes in the senate do show). 

Has Vote information:
https://nyassembly.gov/leg/?default_fld=%0D%0A&leg_video=&bn=A9275&term=2021&Summary=Y&Actions=Y&Committee%26nbspVotes=Y&Floor%26nbspVotes=Y

Missing Vote information:
https://legislation.nysenate.gov/api/3/bills/2021/A9275

p.s. thanks for your awesome work making this data available; I'm trying to build a view to score members sponsorship and voting based on select bills - and this is one limiting factor

https://legislation.support/jehiah-nyc/scorecard/ny-assembly
https://legislation.support/jehiah-nyc/scorecard/nysenate

**Comment by KevinCaseiras** [comment]
Hey @jehiah glad to hear your putting our data to good use.

Unfortunately, we are unable to provide data on Assembly committee and floor votes because we do not have access to that data. You'll have to use the [Assembly website](https://nyassembly.gov/) for that data.
