### ISSUE TITLE
Idea: checksums or digital signatures for statute text

### ISSUE THREAD

**Issue by dogweather** [nysenate/OpenLegislation#124]
I'm kicking around ideas for enabling the end user to verify a website's text against the official API content. E.g., I pull from the API to create this page:

  https://newyork.public.law/laws/n.y._insurance_law_section_3217-d

Now, how can I help site visitors verify that the text is unchanged and up to date? Currently I do two things:

1. I link to the equivalent page at nysenate.gov:

<img width="180" alt="Screenshot 2023-09-22 at 11 01 28 PM" src="https://github.com/nysenate/OpenLegislation/assets/150670/8b83d264-678f-4f5b-af31-4133eacf0184">

2. I wrote this explainer-style page:

https://newyork.public.law/laws/information-about-updates

### I'd like to take this further

Somehow - maybe a browser plugin - that'd check the text after loading the page. My current best idea is to reduce the two texts to a normalized whitespace and then do a diff. It'd reflect the result to the user, and on demand show how it arrived at that result.

Now, if the API included e.g. a SHA checksum or public key-based signature, that could enable more scenarios.

**Comment by KevinCaseiras** [comment]
Hi @dogweather,

We actually have an api endpoint for getting a list of updates to a specific law sub document (looks like this is missing from our documentation though).
i.e. https://legislation.nysenate.gov/api/3/laws/ISC/3217-D/updates 

Does this help?

**Comment by dogweather** [comment]
Thanks, that sounds very useful, I'll check it out. I'm also getting pretty good results doing this on-the-fly diff. Here, it's showing that on my site, I've removed the redundant (?) title from the body text that some statutes have.

<img width="783" alt="Screenshot 2023-09-25 at 11 05 13 AM" src="https://github.com/nysenate/OpenLegislation/assets/150670/798381df-0526-4f39-b87f-063dfa13a096">

The real challenge IMO is how to provide anything of meaning to the end user. I.e., if you're wanting confirmation that a site is accurate, it doesn't help much for the site to tell you, "Yep, I'm accurate!" :-)

So I'm thinking about a "show me" page where the plugin walks through how it arrived at its conclusion. Kind of like some AI's do.

**Comment by KevinCaseiras** [comment]
hmm, yeah that's an interesting problem. The text diff sounds like a reasonable solution, we actually do something similar internally to check bill text accuracy.

Let me know how it goes.

That website looks amazing btw, well done!

**Comment by dogweather** [comment]
> That website looks amazing btw, well done!

Thanks, I really appreciate it.
