### ISSUE TITLE
Timing for available data

### ISSUE THREAD

**Issue by kenanokeefe** [nysenate/OpenLegislation#126]
As of the end of last week we are noticing a delay with data from the API vs the Assembly website.

There are some bills missing, i.e. S 7667:
https://www.nysenate.gov/legislation/bills/2023/S7667
https://assembly.state.ny.us/leg/?bn=S07667&term=2023&Summary=Y&Actions=Y

There are some actions missing, i.e. A 7043:
https://www.nysenate.gov/legislation/bills/2023/A7043
https://assembly.state.ny.us/leg/?bn=A7043A&term=2023&Summary=Y&Actions=Y

**Comment by KevinCaseiras** [comment]
Thanks for the report.

We did have a processing issue during the last week which has been resolved. Everything should be up to date.

Let us know if you see any other issues.
