### ISSUE TITLE
Limit parameter is required for meetings endpoint, but not documented

### ISSUE THREAD

**Issue by jessemortenson** [nysenate/OpenLegislation#127]
The [committee meetings endpoint](https://legislation.nysenate.gov/static/docs/html/agendas.html#get-a-list-of-committee-meeting-times-in-a-time-range) requires a URL query parameter `limit` but this is not mentioned in the documentation. 

BTW great work on this API, a great resource for open data!

**Comment by KevinCaseiras** [comment]
This was a bug in the agenda meetings API endpoint which is now fixed. `limit` will now default to 25 if it is not passed it.

Thanks for reporting this!
