### ISSUE TITLE
Senate member contact info

### ISSUE THREAD

**Issue by elliott-king** [nysenate/OpenLegislation#128]
Looking through the [member API](https://legislation.nysenate.gov/static/docs/html/members.html), members have a public email, but no phone number. 

This information is elsewhere [on the nyassembly website](https://nyassembly.gov/mem/), but I am having trouble finding it in the API. Is there a way to retrieve phone numbers & offices through this API or another?

**Comment by KevinCaseiras** [comment]
Hey @elliott-king, thanks for the question.

Open Legislation is not a canonical source of information for members. The information we do have is manually entered from other sources and may be incomplete or out of date.

For Senator data, I can point you to https://www.nysenate.gov/senators.json, though to get phone numbers you'll have to browse the website at https://www.nysenate.gov/senators-committees.

For Assembly data, I'm not aware of any source besides their website - https://nyassembly.gov/mem/.
