### ISSUE TITLE
Add demo key information to docs

### ISSUE THREAD

**Issue by avalatea** [nysenate/OpenLegislation#129]
Hi! Sometimes I want to log the url that is causing errors but I would like to prevent leaking the API key. It would be nice if there is a `DEMO_KEY` with a very low ratelimit for logging purposes.

```
https://legislation.nysenate.gov/api/3/bills/2023/A%204737?detail=true&key=DEMO_KEY
```

**Comment by KevinCaseiras** [comment]
Hi @avalatea,

Thanks for your suggestion. That would be convenient, however it is not supported by our current infrastructure and we are not able to add it at this time.

I'm going to close this issue, but if you run into issues feel free to open a new issue and just include the url with the key removed.

Thanks
