### ISSUE TITLE
Section Symbol Appearing as Superscript '3'

### ISSUE THREAD

**Issue by jurisware-devel** [nysenate/OpenLegislation#130]
For some statutes in the Laws JSON API, the section symbol is appearing as the number '3' in superscript.  See, for example, CPL section 1.20 at:  https://legislation.nysenate.gov/api/3/laws/CPL?full=true.

{
                      "lawId" : "CPL",
                      "lawName" : "Criminal Procedure",
                      "locationId" : "1.20",
                      //omitted
                      "text" : "³ 1.20 Definitions of terms of general use in this chapter...."

**Comment by JacobKeegan** [comment]
Good find, thanks for catching it! This should now be fixed for most law documents (such as CPL section 1.20), and will be fixed for the rest shorty.

**Comment by JacobKeegan** [comment]
This is now fixed for all law documents.
