### ISSUE TITLE
Article/Titles in small case is not parsed

### ISSUE THREAD

**Issue by aaru** [nysenate/OpenLegislation#14]
If an Title or Article is in Small case in then it is not parsed. (http://public.leginfo.state.ny.us/lawssrch.cgi?NVLWO)
Ex:  VAT - Vehicle and Traffic -> Title 1> Article 1 - (100 - 161) Words and phrases defined. 
All the articles are in CAPITAL letters and are parsed correctly, but the above Article 1 is in small case and this is stripped of and when i query for data from API, i get blank title for Article 1.

**Comment by KevinCaseiras** [comment]
Thanks for your report. We have made a lot of improvements to law titles recently and this was included in one of the fixes.
