### ISSUE TITLE
An invalid API key issue

### ISSUE THREAD

**Issue by Fenhanwang** [nysenate/OpenLegislation#18]
Hey, Guys! I am using your guys' API system for almost a year and it is an awesome project.
Just a small issue happened today.
I was able to use the API service last night. But I get a _No search results were found A valid API key is needed to fulfill this request_ error message on the [website](http://legislation.nysenate.gov/) now.

I don't think the API key is invalid since I have  been using that for a long time

**Comment by gaoyike** [comment]
? could you provide more information ?

**Comment by Fenhanwang** [comment]
sorry, I hit ctrl+Enter wrong
@gaoyike

**Comment by Fenhanwang** [comment]
![image](https://cloud.githubusercontent.com/assets/4448522/20069513/ee0411d4-a4ea-11e6-8e85-4a26a6707361.png)

The snapshot above is what I saw on the [website](http://legislation.nysenate.gov/) after I log in using my API key

**Comment by stouffers** [comment]
@Fenhanwang just curious, are you able to call the bill search api directly using your key?
Instructions here: http://legislation.nysenate.gov/static/docs/html/bills.html#search-for-bills

**Comment by Fenhanwang** [comment]
@McSquirrel

**Comment by Fenhanwang** [comment]
@McSquirrel 
Hi, I have a API script following the instruction and I cannot use that script either.
It worked last week.
Do you guys change the instruction? or not

**Comment by Fenhanwang** [comment]
@McSquirrel 
Oh, wait. it works again!
Thank You!

**Comment by Fenhanwang** [comment]
@McSquirrel 
the script worked. As long as the script works, it is OK for me
