### ISSUE TITLE
Status 400 on previously working query

### ISSUE THREAD

**Issue by foggy1** [nysenate/OpenLegislation#19]
Previously, after a server update, the following query started requiring the wildcard for nested data, and has worked since. 

"http://legislation.nysenate.gov/api/3/bills/2013/search?term=\*voteType:%27FLOOR%27%20AND%20year:2014&key=***"

I just checked our app, though, and this call is now being met with a status 400.  Did something else change in elastic search?

**Comment by kzalewski** [comment]
Hi Austin,

I just checked this API call using the exact URL that you provided (but replacing "***" with a valid API key), and it worked fine.  I received a proper JSON response from the server.

Can you try it again.

**Comment by foggy1** [comment]
It looks like the call is now being much pickier about the escape for the wildcard itself being valid URI now.  When it changes to %5C it seems to work.  Let me change the codebase and see if this is all that it was.

**Comment by foggy1** [comment]
... yup that appears to be it.  Good grief, note to self: if the project breaks in any way, it's this darn wildcard.
