### ISSUE TITLE
About missing bill on Senate website but not missing on House website

### ISSUE THREAD

**Issue by Fenhanwang** [nysenate/OpenLegislation#20]
Hey, Guys! Sorry to bother your guys.
My team found that S2007 2017 (senate bill 2007) show up on House website [S2007](http://assembly.state.ny.us/leg/?default_fld=&leg_video=&bn=S02007&term=2017&Summary=Y&Actions=Y) but it is not on the senate website [search page](https://www.nysenate.gov/search/legislation?searched=true&type=f_bill&bill_printno=S02007&bill_session_year=2017&page=1) and not in the API

**Comment by stouffers** [comment]
@Fenhanwang We have been experiencing some issues that have delayed data processing.  Sorry for any issues this may have caused. 
 S2007 is now up on Open Legislation: https://legislation.nysenate.gov/bills/2017/S2007

**Comment by Fenhanwang** [comment]
Thanks guys! You are one of the best team I ever met!
