### ISSUE TITLE
It's not a issue but a question

### ISSUE THREAD

**Issue by Fenhanwang** [nysenate/OpenLegislation#22]
Hey, Guys!
Thank you for keep improving the API.It's really a good tool and I appreciate it.
I have a small question about the agendas part in the API call.
So basically, I know NY Senate website has the agenda in the future.

But, correct me if I'm wrong, I didn't see the future agenda data in the API call.
If possible, could you guys put the future agenda data in the API call? like what Senate website did

**Comment by stouffers** [comment]
Hi @Fenhanwang,

You can retrieve all agenda data shown on NYSenate.gov from Open Legislation.  
I now realize that our agenda api docs are wrong and incomplete ...   Sorry about this, I will update these soon.

In the meantime, here are some api endpoints you can use to get the data:

Get list of agendas for a given year
`/api/3/agendas/{year}
`

Get an agenda
`/api/3/agendas/{year}/{agendaNo}
`

Get agenda updates
`/api/3/agendas/updates/{from}/{to}
`

**Comment by Fenhanwang** [comment]
@McSquirrel Thank you very much and your guys are always responsible. I appreciate.
