### ISSUE TITLE
A potential IP block on production server

### ISSUE THREAD

**Issue by Fenhanwang** [nysenate/OpenLegislation#23]
Hey, guys! 
It's me again. lol
On our production server, we send requests to the API maybe 4 or 5 times per day.
Today, I use `CURL` to test and get `Could not resolve host: legislation.nysenate.gov` error.

I use the same command and test on local. it works well. I can even open the JSON through my browser.

I assume maybe it's an IP block?
If it's not good to send request 5 times per day, we would eliminate that behavior.

**Comment by KevinCaseiras** [comment]
I believe we were having some DNS issues on June 7th.

I'm assuming this has resolved itself, if your still having issues please let us know.
