### ISSUE TITLE
Issue loading Assembly Members

### ISSUE THREAD

**Issue by kormic911** [nysenate/OpenLegislation#24]
When calling http://legislation.nysenate.gov/api/3/members/2017/assembly?key=<key>&full=true&limit=200 I see the following error:

`{
"success": false,
"message": "The member was not found",
"responseType": "error",
"errorCode": 151
}`

**Comment by KevinCaseiras** [comment]
Hi @kormic911,

Thanks for bringing this to our attention. It seems one of our caches had some stale data in it. Everything has been refreshed and should be working. Please let us know if you have any other issues.
