### ISSUE TITLE
Scheduled downtime?

### ISSUE THREAD

**Issue by pelzhaus** [nysenate/OpenLegislation#27]
http://legislation.nysenate.gov/ appears to be down right now and I wanted to check if this is scheduled? If it is, do you typically do maintenance around this time of the week? Thanks!

**Comment by kzalewski** [comment]
Hi there.  We are working to bring the server back online.  The server was rebooted earlier, which usually takes about 2 minutes, back it never came back up.  So this downtime was not scheduled, and I'm hoping that we'll be back up in an hour or so.

**Comment by kzalewski** [comment]
Our OpenLegislation server was brought back online around 10:30pm last night, just in time to ring in the new year!  Please let me know if you're still having difficulty connecting.

**Comment by pelzhaus** [comment]
Working great now, thanks!
