### ISSUE TITLE
Charles / Inez barron data mixup

### ISSUE THREAD

**Issue by pelzhaus** [nysenate/OpenLegislation#28]
Hi I believe there is an error for the 60th district assembly seat, http://legislation.nysenate.gov/api/3/members/2017/493 returns data for Inez Barron who was succeeded by her husband Charles Barron in 2015. The 2015 session also returns Inez instead of Charles.

At least a call to http://legislation.nysenate.gov/api/3/members/2017 gives 493 as the ID of the assembly member in the 60th district

Thanks!

**Comment by jpelton-stroud** [comment]
The Charles / Inez issue is still here, and SD 57 is another - API `members-session list` Response says *Cathy Young*, but *George Borrello* won the special election this past November.

Assuming these are issues passed in from LBDC or "Member Services", how do we get the "bad data" message to the right place?

**Comment by KevinCaseiras** [comment]
Thank you both for reporting these issues.

We have made some corrections to our member data to fix these issues.

This is the correct place to report issues with member data. Most of our member data is manually entered, so please continue to report any inconsistencies you find.

Thanks!
