### ISSUE TITLE
Just wanna confirm whether it's your server down time or it's something specific on my side 

### ISSUE THREAD

**Issue by Fenhanwang** [nysenate/OpenLegislation#29]
Hey, Guys.
Again, Thank you very much for the good API and your guys are always very responsive. 
We cannot use your API this morning till now. Just want to make sure it's your server downtime but not us.

**Comment by Fenhanwang** [comment]
saw it turned back on. Thank you guys

**Comment by kzalewski** [comment]
Our server had a problem this morning, and the application was left in a strange state where it could not accept new connections.  I am reviewing the logs now to determine what caused the issue, but yes, everything should be running fine again.
