### ISSUE TITLE
Question re: Data Quality

### ISSUE THREAD

**Issue by protasm** [nysenate/OpenLegislation#30]
Hello,

I have been using the Open Legislation REST API for a couple weeks now to easily load Laws metadata and statutory text into my iPhone app.  One question, is the development team open to feedback regarding data quality?  For example, with Rule 305 of the Civil Practice Law an Rules (CVP), the title of the Rule also includes some of the text of the Rule itself:

               "lawId" : "CVP",
              "lawName" : "Civil Practice Law & Rules",
              "locationId" : "305",
              "title" : "Rule 305. Summons; supplemental summons, amendment. (a) Summons; supplemental summons. A summons shall specify the basis of the venue d...",
              "docType" : "SECTION",
              "docLevelId" : "305",
              "activeDate" : "2014-09-22",
              "sequenceNo" : 44,
              "repealedDate" : null,
              "fromSection" : "305",
              "toSection" : "305",

As I encounter what I believe to be data quality issues, can I compile them into emails and submit them for review?  If so, can you let me know which address to use?

Thank you,

Jon Stroble
Asst. Public Defender
Oneida County

**Comment by KevinCaseiras** [comment]
Hi Jon,

Looks like no one ever got back to you on this, I apologize for that.

We are aware of incorrect titles in our law data. We have made a lot of improvements on them recently but they are still not perfect.

No need to report incorrect titles to us, but if you find anything else wrong we would welcome your feedback.

**Comment by protasm** [comment]
Thanks for getting back to me, I do appreciate it very much.
