### ISSUE TITLE
Question: BaseURL for member.imgName?

### ISSUE THREAD

**Issue by jpelton-stroud** [nysenate/OpenLegislation#44]
What's the base URL for the `imgName` property of the `member` object returned by the API?  Or is there a separate method/API call for returning the image file itself that I'm not finding in the docs?

**Comment by KevinCaseiras** [comment]
You can get the image from the following endpoint: `/static/img/business_assets/members/mini/{imgName}`
i.e. https://legislation.nysenate.gov/static/img/business_assets/members/mini/527_richard_gottfried.jpg

We'll work on getting this added to our documentation.

Thanks!
