### ISSUE TITLE
sessionMemberId 1312 cited but not found

### ISSUE THREAD

**Issue by jpelton-stroud** [nysenate/OpenLegislation#45]
Updates Queries on A5308 and A2594 cite a multisponsor with `sessionMemberId` **1312**, but a Member Search Query for that Id returns an empty list.  A full [2019 Members Query](https://legislation.nysenate.gov/api/3/members/2019?limit=1000&key=) also doesn't return a member with `sessionMemberId` 1312.

[A5308 Updates Query](https://legislation.nysenate.gov/api/3/bills/2019/A5308/updates?filter=multisponsor&key=)
````json
{
  "id" : {
    "basePrintNo" : "A5308",
    "session" : 2019,
    "basePrintNoStr" : "A5308-2019"
  },
  "contentType" : "BILL",
  "sourceId" : "2019-02-08-15.57.33.926536_LDSPON_A05308.XML-1-LDSPON",
  "sourceDateTime" : "2019-02-08T15:57:33.926536",
  "processedDateTime" : "2019-02-08T16:01:11.206671",
  "action" : "Insert",
  "scope" : "Bill Amendment Multi Sponsor",
  "fields" : {
    "Created Date Time" : "2019-02-08 16:01:11.206671",
    "Bill Amend Version" : " ",
    "Sequence No" : "31",
    "Session Member Id" : "1312"
  },
  "fieldCount" : 4
}
````

[A2594 Updates Query](https://legislation.nysenate.gov/api/3/bills/2019/A5308/updates?filter=multisponsor&key=)
````json
{
  "id" : {
    "basePrintNo" : "A5308",
    "session" : 2019,
    "basePrintNoStr" : "A5308-2019"
  },
  "contentType" : "BILL",
  "sourceId" : "2019-02-08-15.57.33.926536_LDSPON_A05308.XML-1-LDSPON",
  "sourceDateTime" : "2019-02-08T15:57:33.926536",
  "processedDateTime" : "2019-02-08T16:01:11.206671",
  "action" : "Insert",
  "scope" : "Bill Amendment Multi Sponsor",
  "fields" : {
    "Created Date Time" : "2019-02-08 16:01:11.206671",
    "Bill Amend Version" : " ",
    "Sequence No" : "31",
    "Session Member Id" : "1312"
  },
  "fieldCount" : 4
}
````

[sessionMemberId:1312](https://legislation.nysenate.gov/api/3/members/2019/search?term=sessionMemberId:1312&key=)
````json
{
  "success" : true,
  "message" : "",
  "responseType" : "empty list",
  "total" : 0,
  "offsetStart" : 1,
  "offsetEnd" : 0,
  "limit" : 50,
  "result" : {
    "items" : [ ],
    "size" : 0
  }
}
````

**Comment by KevinCaseiras** [comment]
Thanks for the report @jpelton-stroud.

It appears we have a bug where our various APIs use an inconsistent `session_member_id` for members that have multiple rows in our `session_member` table.

I have created an issue internally to work on this, but until its fixed, here are the 2019 records that will be effected by this bug.

| session_member_id | member_id | lbdc_short_name | session_year | district_code | alternate |
|------|-----------|-----------------|--------------|---------------|-----------|
| 1238 |      1240 | RAYNOR          |         2019 |            18 | t|
| 1311 |       520 | ROSENTHAL       |         2019 |            67 | t|
| 1312 |       520 | ROSENTHAL L     |         2019 |            67 | f|
| 1314 |       527 | GOTTFRIED       |         2019 |            75 | t|
| 1315 |       527 | GOTTFRIED R     |         2019 |            75 | f|
| 1328 |       591 | PEOPLES-STOKE   |         2019 |           141 | f|
| 1329 |       591 | PEOPLES-STOKES  |         2019 |           141 | t|
| 1429 |       545 | ZEBROWSKI       |         2019 |            96 | f|
| 1442 |       545 | ZEBROWSKI O     |         2019 |            96 | t|
| 1504 |      1240 | DARLING         |         2019 |            18 | f|

**Comment by jpelton-stroud** [comment]
Thanks for the heads up!

**Comment by KevinCaseiras** [comment]
You can get better results from the member search API if you use `sessionShortNameMap.yyyy.sessionMemberId=####` as your search term. Where `yyyy` is the session year and `####` is the session member id.

For the example you provided, the query would be:
`/api/3/members/search?term=sessionShortNameMap.2019.sessionMemberId:1312`
