### ISSUE TITLE
search?term=publishedDateTime:[2014-01-01%20TO%202014-01-02] throws HTTP 400

### ISSUE THREAD

**Issue by jpelton-stroud** [nysenate/OpenLegislation#47]
Not sure if this is actually just a malformed or erroneous example in the docs, but the very last example under [Search for Bills](https://legislation.nysenate.gov/static/docs/html/bills.html#search-for-bills) is
````
(GET) /api/3/bills/2013/search?term=publishedDateTime:[2014-01-01 TO 2014-01-02]&sort=publishedDateTime:ASC
````
Which throws `HTTP Status 400 – Bad Request` when run.  Tried with and without the `key=` field, no change.

Edit to add test link: https://legislation.nysenate.gov/api/3/bills/2013/search?term=publishedDateTime:[2014-01-01%20TO%202014-01-02]&sort=publishedDateTime:ASC

**Comment by jpelton-stroud** [comment]
looks like it's a parsing issue, *this* link *does* work: https://legislation.nysenate.gov/api/3/bills/2013/search?term=publishedDateTime:%5B2014-01-01%20TO%202014-01-02%5D&sort=publishedDateTime:ASC

notice the [brackets] in the search term are replaced with `%5B`

**Comment by KevinCaseiras** [comment]
Thanks for reporting this @jpelton-stroud.

As you noticed, the issue is that `[` and `]` are special characters which must be url encoded when used in a url.

We'll work on clarifying this in our documentation.
