### ISSUE TITLE
  "responseType" : "search-results list" vs   "responseType" : "bill-info list"

### ISSUE THREAD

**Issue by jpelton-stroud** [nysenate/OpenLegislation#48]
- https://legislation.nysenate.gov/api/3/bills/2013?search?term=Gun%20Control returns `  "responseType" : "bill-info list",`
- https://legislation.nysenate.gov/api/3/bills/2013/search?term=publishedDateTime:%5B2014-01-01%20TO%202014-01-02%5D returns `  "responseType" : "search-results list",`

1. Is this intentional?
1. If so, what's the reasoning behind it?

**Comment by KevinCaseiras** [comment]
Hi @jpelton-stroud. It looks like there is a typo in your first url. It should be `2013/search` not  `2013?search`.

This url should give you the results your looking for: https://legislation.nysenate.gov/api/3/bills/2013/search?term=Gun%20Control

**Comment by jpelton-stroud** [comment]
ugh.  thanks for the heads up!
