### ISSUE TITLE
NY Laws API docs "Get a law sub document" shows different response type than what is actually returned

### ISSUE THREAD

**Issue by jpelton-stroud** [nysenate/OpenLegislation#49]
Docs section [_Get a law sub document_](https://legislation.nysenate.gov/static/docs/html/laws.html#get-a-law-sub-document) suggests [this query](https://legislation.nysenate.gov/api/3/laws/EDN/A2/) should return `"responseType": "law-document"`, but I'm seeing `"law-doc-info-detail"`, instead.

Am I missing something again?

**Comment by KevinCaseiras** [comment]
Good catch. This is another issue with our documentation being out of date.

The response you are receiving of `"responseType" : "law-doc-info-detail",` is correct.

**Comment by jpelton-stroud** [comment]
I'm not terribly familiar with restructuredText, but changing one word to another is something I can handle. :P
