### ISSUE TITLE
https support question

### ISSUE THREAD

**Issue by fedex1** [nysenate/OpenLegislation#5]
Thank you for the open legislation project.

This request is to add HTTPS support. 

One question involves the support for HTTPS

HTTPS support is needed because in order to use the HTML5 service workers and have efficient caching of these large responses, HTTPS is the only supported connection.

Also HTTPS support is probably needed for the government api / sites to lessen the probability of man in the middle attacks.

https://www.nysenate.gov/ and
https://www.nysenate.gov/opendata seems to use a certificate from 
http://acquia-sites.com/

message from browser says:

> This is probably not the site you are looking for! You attempted to reach www.nysenate.gov , but 
> instead you actually reached a server identifying itself as acquia-sites.com. This may be caused by a 
> misconfiguration on the server or by something more serious. An attacker on your network could be 
> trying to get you to visit a fake (and potentially harmful) version of www.nysenate.gov. You should not 
> proceed

At https://www.nysenate.gov/opendata
we see

![screen shot 2015-04-26 at 12 31 48 am](https://cloud.githubusercontent.com/assets/167614/7335896/f6d2cb7e-ebab-11e4-8402-b4543697c457.png)

And at open.nysenate.gov there seems to be no SSL support at all.
At https://open.nysenate.gov/
we see

![screen shot 2015-04-26 at 12 38 35 am](https://cloud.githubusercontent.com/assets/167614/7335903/a9cc1d3e-ebac-11e4-8d05-9e76f1672845.png)

**Comment by parkr** [comment]
I would like to see this as well.

**Comment by kzalewski** [comment]
This issue has been resolved since early 2016.  SSL/TLS has been supported on OpenLegislation and the NYSenate.gov for quite some time.

I am closing this issue.
