### ISSUE TITLE
Timing for available data

### ISSUE THREAD

**Issue by kenanokeefe** [nysenate/OpenLegislation#51]
Hello - 

We are noticing a potential delay today with data from the API.

As of right now it appears the total number of bills available for session 2019 is 21938, with the latest bill number being `S8224`.

When spot checking on the NY Assembly website, appears the latest senate bill number at the moment is [S8254](https://nyassembly.gov/leg/?default_fld=%0D%0A&leg_video=&bn=S08254&term=0&Summary=Y&Actions=Y).

Appears that the bills not yet available were introduced on 4/27. 

Thanks!
Kenan

P.S. We love your API. It's still the best one across all the states.

**Comment by KevinCaseiras** [comment]
Thanks for reporting this!

It appears we were having a bit of an issue with our data processing. Everything should be up to date now.

**Comment by kenanokeefe** [comment]
Seeing up to `S8254` now! Thanks for the reply!
