### ISSUE TITLE
What's in a name? Some Member page URIs don't match fullName fields returned by API

### ISSUE THREAD

**Issue by jpelton-stroud** [nysenate/OpenLegislation#53]
The "API vs site admin" line on this one is a little blurry to me, but it affects both nysenate.gov and nyassembly.gov and is directly related to the population of the `fullName` field returned by API member queries, so here you go:

````typescript
export const memberURI = (chamber: string, name: string): string => {
  // replace whitespace with dashes, then strip insignificant punctuation
  const nameStr = name.replace(/ /g, '-').replace(/\.|\,/g, '');
  return chamber === 'SENATE'
    ? `https://www.nysenate.gov/senators/${nameStr.toLowerCase()}`
    : chamber === 'ASSEMBLY'
    ? `https://nyassembly.gov/mem/${nameStr}`
    : '';
};
````
The above works pretty well for the majority of members:
* [`"fullName" : "Catharine Young"`](https://legislation.nysenate.gov/api/3/members/2019/414) -> https://www.nysenate.gov/senators/catharine-young
* [`"fullName" : "Michaelle C. Solages"`](https://legislation.nysenate.gov/api/3/members/2019/673) ->  https://nyassembly.gov/mem/Michaelle-C-Solages
* [`"fullName" : "George Borrello"`](https://legislation.nysenate.gov/api/3/members/2019/1370) -> https://www.nysenate.gov/senators/george-borrello, which then resolves to https://www.nysenate.gov/senators/george-m-borrello (so i don't have the "correct" URI, but it resolves so i don't care that much)

A significant minority, however, _don't_ work, either because the API call doesn't include appropriate initials/suffixes, or the target domain uses a partial name rather than the full name for the member's URI:
* [`"fullName" : "Kenneth Blankenbush"`](https://legislation.nysenate.gov/api/3/members/2019/631) -> https://nyassembly.gov/mem/Kenneth-Blankenbush, which ___fails___ to resolve, b/c KB's URI is https://nyassembly.gov/mem/Ken-Blankenbush
* [`"fullName" : "George Amedore"`](https://legislation.nysenate.gov/api/3/members/2019/892), but [Amedore's _actual_ URI includes the "Jr" suffix](https://www.nysenate.gov/senators/george-amedore-jr), which isn't in the API response, so it fails, too.

Would be nice if everybody got on the same page and worked together, IMHO. Cheers!

**Comment by KevinCaseiras** [comment]
That would be nice :heart_eyes:.

Unfortunately, the Senate and Assembly are separate and independent entities. So our url schema's will never match up with theirs 100%.

As far as the Senate websites are concerned, it may help to get your member data from Nysenate.gov. They have a json feed available at https://www.nysenate.gov/senators-json. Members in that json feed have a field `open_leg_id` which is the same as the Open Legislation member id.
