### ISSUE TITLE
Filling the data gaps in the Directory data

### ISSUE THREAD

**Issue by vernnyc** [nysenate/OpenLegislation#60]
When I pull a full member list using: 

> https://legislation.nysenate.gov/api/3/members/2020?full=true&limit=300&key="mykey"

I get 221 records, but only 49 of them include email information, the rest are either blank or "null" for that field.   Is there any plan to get the missing data?  Any insight on what determines whether there is an email address, an empty field, or the word null?

Thanks!

**Comment by KevinCaseiras** [comment]
Hey Vernon

Your right, we do have some gaps in our member data, we do plan on improving this in the future.
There is no significant difference between an email of `null` or `""` and no specific reason why some members are missing email addresses.

In the meantime, I can refer you to https://www.nysenate.gov/senators-json for incumbent senator information and https://nyassembly.gov/mem/ for the assembly.
