### ISSUE TITLE
Timing for 2021 session data

### ISSUE THREAD

**Issue by kenanokeefe** [nysenate/OpenLegislation#62]
Hello -

We are noticing a potential delay today with 2021 session data from the API.

Appears that bills such as [S212](https://www.nysenate.gov/legislation/bills/2021/S212) and [A339](https://www.nysenate.gov/legislation/bills/2021/A339) are not available today via the https://legislation.nysenate.gov/api/3/bills/2021 endpoint.

Thanks,
Kenan

**Comment by KevinCaseiras** [comment]
Thank you for the report,

We have fixed an issue that was preventing some 2021 bills from being cached properly. You should now see the correct results at that endpoint.

Let us know if you have any other issues.

**Comment by kenanokeefe** [comment]
Thanks!
