### ISSUE TITLE
Ability to analyze the open legislation data and questions

### ISSUE THREAD

**Issue by fedex1** [nysenate/OpenLegislation#7]
Hi,

I've extracted all the bill and actions data and placed it in a publicly available SQL database for analysis.

See https://bigquery.cloud.google.com/table/personal-real-estate:nys.bills_actions (requires an account and includes a high free daily quota)

Here are some blog entries containing analysis and questions:
- http://timingblog.brooklynmarathon.com/2015/05/questions-about-nys-senate-api.html
- http://timingblog.brooklynmarathon.com/2015/05/focus-on-new-york-state-legislature.html

From the blog entries:

Focus on New York State Legislature open data: Is 16,000 bill actions in one day correct?
See http://open.nysenate.gov/legislation/search/otype%3Aaction+AND+when%3A%5B1262736000000+TO+1262822399000%5D+AND+active%3Atrue/1/20?sort=&sortOrder=true

**We have a question, it appears that there were approximately 16,000 bill actions on 1/6/2010.  Is that correct?**

![image](https://cloud.githubusercontent.com/assets/167614/7785352/3a4b9ec6-015a-11e5-9339-0bedec40447b.png)

This is from the NY Senate site:

Questions about the NYS Senate API
Some questions that you may have as a citizen of New York State are:
- How many legislative bills are produced each year?
- How many legislative bills are passed each year?
  Those questions seem to be very basic and necessary to understand our legislative process in New York State.

Here's some data from http://open.nysenate.gov/legislation/advanced/ and http://openlegislation.readthedocs.org/en/latest/

See http://demo.redash.io/queries/278#349

**This is Count of New York State Legislative Bills per year.  It appears to vary between 20,000 and 10,000 in alternating years. Is this possible?**

![image](https://cloud.githubusercontent.com/assets/167614/7785334/afb6fe22-0159-11e5-8043-927aff7f5d3b.png)

But if we look at bill actions we see:

http://demo.redash.io/queries/287#366 (requires an account)

**The bill actions seems to be consistently in the 60,000 range.  That seems like a lot of actions.**

![image](https://cloud.githubusercontent.com/assets/167614/7785342/e42911cc-0159-11e5-9971-332d8929127e.png)

Who are the top sponsors of these actions?

See http://demo.redash.io/queries/291#369

![image](https://cloud.githubusercontent.com/assets/167614/7785345/f57774aa-0159-11e5-820d-b5378264139f.png)

**Comment by kzalewski** [comment]
The data in this issue is referring to the old open.nysenate.gov website, which was OpenLegislation v1.0.

We have been supporting OpenLegislation 2.x (currently, 2.12) for the last several years.

If this issue is still persistent in OL 2.x, please open a new ticket.

For now, this issue is closed.
