### ISSUE TITLE
Simple Question: how can we create a visualization that shows % of bills that become law?

### ISSUE THREAD

**Issue by fedex1** [nysenate/OpenLegislation#8]
It would be nice to know of the 60,000 bill actions and ~ 20,000 bills each year, how many actually become law?

Also how many bills actually have public hearings and public input?

Is this information available in the API?

This type of information would be very helpful.

It would be nice if the API site included charts and visualizations to help people understand the data.

Thanks for the API!

**Comment by kzalewski** [comment]
OpenLegislation is a legislative data service.  It provides the legislative data itself, but it does not provide any type of interpretation or visualization of such data.

It would be up to our users to implement software that could generate charts or graphs based on the data itself.

I am closing this issue.
