### ISSUE TITLE
LAW API question

### ISSUE THREAD

**Issue by fedex1** [nysenate/OpenLegislation#9]
Thank you very much for the LAW API.

I have a question about the usage.

I did the following:
* download the full ENV law for 2014-10-01
* also downloaded full ENV law for 2015-05-23

I see at http://nygovernorstg.prod.acquia-sites.com/sites/governor.ny.gov/files/atoms/files/GPB1IVORYCHAPTERAMENDMENTBILL.pdf that shows the ENV 11-0535-A was modified recently to read

* d. the ivory article or rhinoceros horn is part of a musical

*INSTEAD OF*

* d. the ivory article or rhinoceros horn is less than twenty percent by volume

I expected to see the old text in the 2014-10-01 version but I see the new text in both the 2014-10-01 text and the 2015-05-23 text

Is this an issue or is it something that is misunderstood.

Thanks.

Here are the commands:

```
$ curl "http://openleg-dev.nysenate.gov/api/3/laws/ENV?date=2014-10-01&full=true&key=KEY-HERE"  |tee lawlog_2014-10-01.txt

$ grep -c "rhinoceros horn is part of a musical"  lawlog_2014-10-01.txt lawlog_2015-05-23.txt
lawlog_2014-10-01.txt:1
lawlog_2015-05-23.txt:1



```

**Comment by ash858** [comment]
This bill hasn't been signed into law yet. http://openleg-dev.nysenate.gov/bills/2015/A6071

**Comment by fedex1** [comment]
@ash858 thank you very much that helps clear things up.   Also the new site is very very helpful and thank you for all. 

What I'd like to do is show all the actions on all the bills for a given time period on one time line.  

This might show how many bills actually become law and how many die. 

Thanks to API I'll see what I can come up with.

**Comment by ash858** [comment]
We have a search api that you could use to figure out those numbers.

Bills signed into law: /api/3/bills/search?term=signed:true
or for a specific session year: /api/3/bills/2015/search?term=signed:true

If you wanted to know which bills passed during a specific date range try
/api/3/bills/search?term=signed:true AND status.actionDate:[2015-01-01 TO 2015-02-01] 

Also, for resolutions you would want to search with 'adopted:true' instead.

Hope that helps.

**Comment by fedex1** [comment]
Yes.  Thank you very much!
